# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'my-app/pom.xml'
    goals: package
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Docker@2
  inputs:
    containerRegistry: 'ravishay_docker_hub'
    repository: 'ravishay/maven-hello-world'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: latest

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'ravishay_docker_hub'
    command: 'login'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker run ravishay/maven-hello-world:latest